### ISSUE TITLE
Integration Tests With Insufficient Error information

### ISSUE THREAD

**Issue by reid-spencer** [lightbend/akkaserverless-java-sdk#726]
I'm running an integration test via gitlab that fails with an unhelpful error message:
```
[info]   The future returned an exception of type: io.grpc.StatusRuntimeException, with message: UNKNOWN: ERROR: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. (GatewayServiceActionIntegrationSpec.scala:36)
```
This is from akkaserverless-java-sdk using the Scala SDK v0.10.0. 

Here is the full log. Note the "TRANSIENT_FAILURE" message followed shortly by "SHUTDOWN" and then the message "UNAVAILABLE".  Also, the patience config, if that matters is:
```scala
  implicit private val patience: PatienceConfig =  PatienceConfig(Span(60, Seconds), Span(500, Millis))
``` 
Here's the full log:
```
2021-11-19 16:46:57,979 INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
2021-11-19 16:46:58,122 DEBUG 🐳 [gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1] - Starting container: gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1
2021-11-19 16:46:58,123 DEBUG 🐳 [gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1] - Trying to start container: gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1 (attempt 1/1)
2021-11-19 16:46:58,123 DEBUG 🐳 [gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1] - Starting container: gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1
2021-11-19 16:46:58,124 INFO  🐳 [gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1] - Creating container for image: gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1
2021-11-19 16:46:58,163 INFO  🐳 [gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1] - Starting container with ID: 28eab1641043c1d914d94c1eeb1099c6f155bce18c4f2e1ea4164077b0418a3f
2021-11-19 16:46:58,450 INFO  🐳 [gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1] - Container gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1 is starting: 28eab1641043c1d914d94c1eeb1099c6f155bce18c4f2e1ea4164077b0418a3f
2021-11-19 16:47:04,805 INFO  com.akkaserverless.javasdk.impl.DiscoveryImpl - Received discovery call from [akkaserverless-proxy-core 0.8.1] at [localhost] supporting Akka Serverless protocol 0.8
2021-11-19 16:47:07,409 INFO  🐳 [gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1] - Container gcr.io/akkaserverless-public/akkaserverless-proxy:0.8.1 started in PT9.286554S
2021-11-19 16:47:08,380 DEBUG com.yoppworks.coinage.tenant.DefaultTenantServiceClient - monitoring with state IDLE and connectionAttempts 0
2021-11-19 16:47:08,448 DEBUG com.yoppworks.coinage.tenant.DefaultTenantServiceClient - monitoring with state CONNECTING and connectionAttempts 0
2021-11-19 16:47:08,458 DEBUG com.yoppworks.coinage.tenant.DefaultTenantServiceClient - monitoring with state TRANSIENT_FAILURE and connectionAttempts 0
2021-11-19 16:47:08,834 DEBUG com.yoppworks.coinage.tenant.DefaultTenantServiceClient - monitoring with state SHUTDOWN and connectionAttempts 1
[info] GatewayServiceActionIntegrationSpec:
[info] GatewayServiceAction
[info] - should create a tenant *** FAILED ***
[info]   The future returned an exception of type: io.grpc.StatusRuntimeException, with message: UNKNOWN: ERROR: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. (GatewayServiceActionIntegrationSpec.scala:36)```

One last clue: this is the only "Action" integration test, 4 other entity integration tests passed without issue.

**Comment by reid-spencer** [comment]
FYI, two more clues:
* Line 36 in GatewayServiceActionIntegrationSpec.scala is the call from the integration test to the Action: ` val reply = gateway.createTenant(command).futureValue`
* This integration test works correctly when run locally (not from gitlab)

I have set up DinD the usual way in my GitLab pipeline. Is there something else that needs to be done to run integration tests from GitLab?

FYI: my `.gitlab-ci.yml`
```yaml
default:
  image: yoppworks/docker-scala-sbt:latest

# DinD service is required for Testcontainers
services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: [ "--tls=false" ]

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - test

test:
  script:
    - sbt clean coverage test coverageReport
```
